site_name: Channel
site_description: Channel document
repo_url: https://github.com/liangjingkanji/Channel
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/liangjingkanji
    - icon: fontawesome/brands/qq
      link: https://raw.githubusercontent.com/liangjingkanji/liangjingkanji/master/img/group-qrcode.png

site_author: 劉強東
copyright: Copyright &copy; 2018 - 2023 劉強東
repo_name: GitHub
docs_dir: 'docs'
extra_css:
  - css/extra.css
theme:
  name: material
  custom_dir: docs/material
  favicon: img/book-open.svg
  logo: img/book-open.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
  font: false
  language: zh
  features:
    - navigation.top
    - navigation.prune
    - navigation.footer
    - navigation.instant
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
plugins:
  - offline
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
        - en
        - zh
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 使用: index.md
  - 生命周期: lifecycle.md
  - 前台更新: live.md
  - 切换线程: thread.md
  - 1.x文档: api/index.html